### PR TITLE
fix: implement trade restricting service for node app

### LINKED ISSUE #1336: Trade restricted dialog (for node app)
## Summary

Implement the full trade restricted dialog feature for the **node app** (Android Node / `nodeApp`). The client app implementation was added in PR #1330, but the node app counterpart (`NodeTradeRestrictingAlertServiceFacade`) was stubbed out due to compilation errors blocking the Connect 0.3.2 release.

## Context

- PR #1330 (https://github.com/bisq-network/bisq-mobile/pull/1330) introduced the trade restricted dialog feature for the client app.
- The node app implementation in `apps/nodeApp/src/androidMain/kotlin/network/bisq/mobile/node/common/domain/service/alert/NodeTradeRestrictingAlertServiceFacade.kt` failed to compile with the following errors:
  ```
  Unresolved reference 'AuthorizedAlertDataUtils' (lines 4, 57)
  Unresolved reference 'it' (line 61)
  Unresolved reference 'orElse' (line 62)
  ```
- The implementation was temporarily stubbed to unblock the Connect 0.3.2 release.

## Tasks

- [ ] Investigate the correct utility/mapping for converting `AuthorizedAlertData` in the node app context (replace `AuthorizedAlertDataUtils` with the proper approach, likely using `toDomainOrNull` or similar mapping used in the client app).
- [ ] Implement `NodeTradeRestrictingAlertServiceFacade` fully: subscribe to `alertService.authorizedAlertDataSet` via a `CollectionObserver`, filter for `AppType.MOBILE_CLIENT` trade-restricting alerts, and expose the result as a `StateFlow<AuthorizedAlertData?>`.
- [ ] Ensure the node app compiles and passes all tests with the full implementation.
- [ ] Add or update unit/integration tests for the node app facade as needed.

## References

- Resolves the node app stub introduced in PR #1330
- Related issue: #1047 (Forced upgrade feature)

Requested by @rodvar in https://github.com/bisq-network/bisq-mobile/pull/1330

### PR DESCRIPTION
**Pull request by wodoro**
Reverts [f02d025](https://github.com/bisq-network/bisq-mobile/pull/1330/commits/f02d0257fcc3156232996c65e92af2e44b41479a)

Resolves #1336

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved trade-restricting alert handling to properly monitor and refresh alert state when changes occur.
  * Enhanced alert service lifecycle management to ensure alerts are correctly initialized and cleaned up during app operation.

### CODE REVIEW

**Comment by wodoro** [comment]
deleted branch by accident haha

**Review by rodvar — APPROVED** [review]
ACK

thanks wod 👍
